### ISSUE TITLE
使用全局才能访问LinkedIn 国际版

### ISSUE THREAD

**Issue by yanghaigang** [rixCloud-Inc/Clash-Rules#6]
LinkedIn 相关域名被放在domestic 规则下，在使用clash桌面端，使用浏览器访问linkedIn 时会跳转至有审查的中国版，请将LinkedIn.com以及incdn.com移出domestic规则，加到proxy 规则里。(使用surge分会移动客户端也有类似问题，请一并解决).
之前在官网有提单，客服回复让在github 提issue 。

**Comment by ZeroClover** [comment]
请自行使用 Cloud Profile 创建规则条目。
